services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__MongoDB: mongodb://mongo:27017/UbntSecPilot
      MongoDB__DatabaseName: UbntSecPilot
      UDM__BaseUrl: https://192.168.1.1
      UDM__Username: admin
      UDM__Password: ${UDM_PASSWORD:-your_password_here}
      VirusTotal__ApiKey: ${VT_API_KEY:-your_virustotal_api_key_here}
    depends_on:
      - mongo
    ports:
      - "8001:80"
    networks:
      - default

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.BlazorUI
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      WebApiBaseUrl: http://api
    depends_on:
      - api
    ports:
      - "8080:8080"
    networks:
      - default
