services:
  redpanda:
    image: redpandadata/redpanda:v24.1.1
    container_name: redpanda
    hostname: redpanda
    entrypoint: /usr/bin/rpk
    command:
      - redpanda
      - start
      - --mode
      - dev-container
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --set
      - redpanda.auto_create_topics_enabled=true
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,EXTERNAL://localhost:19092
    ports:
      - "9092:9092"
      - "19092:19092"
      - "9644:9644"

  

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.BlazorUI
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      WebApiBaseUrl: http://api
    depends_on:
      - api
    ports:
      - "8501:8080"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  spark-master:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8082:8080"

  spark-worker:
    image: bitnami/spark:3.5
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
    ports:
      - "8083:8081"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__MongoDB: mongodb://mongo:27017/UbntSecPilot
      MongoDB__DatabaseName: UbntSecPilot
      UDM__BaseUrl: https://192.168.1.1
      UDM__Username: admin
      UDM__Password: ${UDM_PASSWORD:-your_password_here}
      VirusTotal__ApiKey: ${VT_API_KEY:-your_virustotal_api_key_here}
    depends_on:
      - redpanda
      - mongo
    ports:
      - "8000:80"

  # (Removed duplicate dashboard service definition)

  sonarqube:
    image: sonarqube:10.6-community
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    depends_on:
      - sonarqube-db
    networks:
      - secpilot-network

  sonarqube-db:
    image: postgres:15
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    networks:
      - secpilot-network

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_db_data:

networks:
  secpilot-network:
    driver: bridge
